[tool.poetry]
name = "project7"
version = "0.1.0"
description = "Django Booking"
authors = ["xziste <17alexdmz99@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.13"
django = "^5.2.8"
gunicorn = "^23.0.0"
psycopg2-binary = "^2.9.11"
python-dotenv = "^1.2.1"
crispy-bootstrap5 = "^2025.6"
django-crispy-forms = "^2.5"
pillow = "^12.0.0"

[tool.poetry.group.dev.dependencies]
black = "^25.9.0"
flake8 = "^7.3.0"
isort = "^7.0.0"
ipython = "^9.7.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
# Максимальная длина строки
line-length = 119
# Файлы, которые не нужно форматировать
exclude = '''
(
  /(
      \.eggs         # Исключить несколько общих каталогов
    | \.git          # в корне проекта
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | dist
  )/
  | foo.py           # Также отдельно исключить файл с именем foo.py
                     # в корне проекта
)
'''