# Generated by Django 5.2.8 on 2025-11-21 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="role",
            field=models.CharField(
                choices=[
                    ("guest", "Гость"),
                    ("critic", "Ресторанный критик"),
                    ("chef", "Шеф-повар"),
                    ("other", "Другое"),
                ],
                default="guest",
                max_length=20,
                verbose_name="Кто вы",
            ),
        ),
    ]
