# Generated by Django 5.2.8 on 2025-11-18 16:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(verbose_name="Дата")),
                ("time", models.TimeField(verbose_name="Время")),
                (
                    "duration_hours",
                    models.PositiveIntegerField(
                        default=2,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ],
                        verbose_name="Продолжительность (часы)",
                    ),
                ),
                (
                    "number_of_guests",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(8),
                        ],
                        verbose_name="Количество гостей",
                    ),
                ),
                ("special_requests", models.TextField(blank=True, null=True, verbose_name="Особые пожелания")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Создано", "Создано"),
                            ("Подтверждено", "Подтверждено"),
                            ("Отменено", "Отменено"),
                            ("Завершено", "Завершено"),
                        ],
                        default="Создано",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
            ],
            options={
                "verbose_name": "Бронирование",
                "verbose_name_plural": "Бронирования",
                "ordering": ["-date", "-time"],
            },
        ),
        migrations.CreateModel(
            name="RestaurantTable",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, unique=True, verbose_name="Название стола")),
                (
                    "table_type",
                    models.CharField(
                        choices=[
                            ("2-seater", "2-местный столик"),
                            ("4-seater", "4-местный столик"),
                            ("6-seater", "6-местный столик"),
                            ("8-seater", "8-местный столик"),
                        ],
                        max_length=20,
                        verbose_name="Тип стола",
                    ),
                ),
                ("capacity", models.PositiveIntegerField(verbose_name="Вместимость")),
                (
                    "location",
                    models.CharField(
                        choices=[("window", "У окна"), ("center", "В центре"), ("terrace", "Терраса"), ("vip", "VIP")],
                        default="center",
                        max_length=20,
                        verbose_name="Расположение",
                    ),
                ),
                ("is_available", models.BooleanField(default=True, verbose_name="Доступен")),
                ("description", models.TextField(blank=True, null=True, verbose_name="Описание")),
            ],
        ),
    ]
