# Generated by Django 5.2.8 on 2025-11-18 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0002_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="booking",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="restauranttable",
            name="location",
            field=models.CharField(
                choices=[("hall", "Зал"), ("terrace", "Терраса")], default="hall", max_length=20, verbose_name="Зона"
            ),
        ),
    ]
