# Generated by Django 5.2.8 on 2025-11-19 05:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="duration_hours",
            field=models.PositiveIntegerField(
                choices=[(1, "1 час"), (2, "2 часа"), (3, "3 часа"), (4, "4 часа")],
                default=2,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)],
                verbose_name="Продолжительность (часы)",
            ),
        ),
    ]
